# Copyright (c) 2017-present SIGHUP s.r.l All rights reserved.
# Use of this source code is governed by a BSD-style
# license that can be found in the LICENSE file.

---
# Source: kubernetes-ingress/templates/controller-crdjob-rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: haproxy-ingress-internal-crdjob
  labels:
    app.kubernetes.io/name: haproxy-ingress-internal-proxy
    app.kubernetes.io/instance: haproxy-ingress
    helm.sh/chart: kubernetes-ingress-1.51.1
    app.kubernetes.io/version: "3.2.8"
    app.kubernetes.io/managed-by: Helm
  annotations:
    helm.sh/hook: post-install,pre-upgrade
    helm.sh/hook-weight: "-5"
    helm.sh/hook-delete-policy: before-hook-creation,hook-succeeded
    argocd.argoproj.io/hook: Sync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: haproxy-ingress-internal-crdjob
subjects:
  - kind: ServiceAccount
    name: haproxy-ingress-internal-crdjob
    namespace: ingress-haproxy
