{
 "title": "cert-manager",
 "description": "Monitors Kubernetes deployments in cluster using Prometheus. Shows overall cluster CPU / Memory of deployments, replicas in each deployment. Uses Kube state metrics and cAdvisor metrics (741)",
 "tags": [ "k8s" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Datasource", "label": "Datasource", "query": "prometheus" },
   {
    "name": "Namespace",
    "query": "label_values(certmanager_certificate_expiration_timestamp_seconds, exported_namespace)"
   },
   {
    "name": "Certificate",
    "query": "label_values(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"},name) "
   }
  ]
 },
 "panels": [
  { "title": "Certificates", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Time Left",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sort_desc( sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"} - time()) BY (name,exported_namespace) )",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  {
   "title": "Certificate Ready Status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(certmanager_certificate_ready_status) BY (condition)",
     "legendFormat": "{{condition}}"
    }
   ]
  },
  {
   "title": "Time Left",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(certmanager_certificate_expiration_timestamp_seconds{exported_namespace=~\"$Namespace\"} - time()) BY (name,exported_namespace)",
     "legendFormat": " {{exported_namespace}} / {{name}}"
    }
   ]
  },
  { "title": "ACME Client", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Overall requests per 1m",
   "type": "graph",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Total requests",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 20, "y": 18 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(certmanager_http_acme_client_request_count)"
    }
   ]
  },
  {
   "title": "create_order_cert",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"create_order_cert\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "authorize_order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"authorize_order\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "get_order",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 26 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"get_order\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "get_authorization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"get_authorization\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "register_account",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"register_account\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "update_registration",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"update_registration\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "accept_challenge",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"accept_challenge\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "wait_authorization",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 42 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(certmanager_http_acme_client_request_count{action=\"wait_authorization\"}[1m])) BY (status)",
     "legendFormat": "{{status}}"
    }
   ]
  }
 ]
}